'use client'


import './globals.css'
import Navbar from '../components/Navbar/Navbar'
import { useState, useRef, useContext, createContext, useEffect } from 'react';
import useMouse from '@react-hook/mouse-position';
import { motion,AnimatePresence } from 'framer-motion';
import styles from './layout.module.scss'

import store from './store';
import { Provider } from 'react-redux'
import { useSelector } from 'react-redux';
import CursorProvider from '../components/Cursor/CursorProvider';

import Footer from '@/components/Footer/Footer';

import Cursorone from '@/components/Cursor2/Cursorone';
import Cursortwo from '@/components/Cursor3/Cursortwo';
import { duration } from '@mui/material';

import { useRouter } from 'next/navigation'
import { usePathname } from 'next/navigation';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }




export default function RootLayout({ children }) {

  const router = usePathname()
  console.log(router.path)


  return (
    <Provider store={store}>

      <html lang="en" style={{ cursor: 'none' }}>
        <body className={styles.overflow_x} >
        <motion.div key={router} initial="pageInitial" animate="pageAnimate" transition={{duration:4}} variants={{
  pageInitial: {
    opacity: 0
  },
  pageAnimate: {
    opacity: 1
  },
}}>



            <div>
            <Cursortwo/>
            

              <Navbar key="navbar" />
              <div key={router}>
              {children}
              
              </div>

              
            </div>
            <Footer />
          {/* </CursorProvider> */}
          </motion.div>
        </body>

      </html>

    </Provider>

  )
}
